apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tasks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tasks
    app.kubernetes.io/part-of: tasks
  name: tasks
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: tasks
status:
  loadBalancer: {}
